name: Create Release Archive

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Generate ZIP
        run: |
          mkdir -p release
          zip -r release/gocxx_errors-${GITHUB_REF_NAME}.zip .

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
